// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(texlocal_syntaxFFI)
import texlocal_syntaxFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_texlocal_syntax_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_texlocal_syntax_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureTexlocalSyntaxInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * An open file's text, mirrored from the editor, and the answers about it.
 */
public protocol SourceDocumentProtocol: AnyObject, Sendable {
    
    /**
     * What to offer at the caret, if anything: commands after a backslash
     * (only once a letter follows unless `explicit`, asked for by the user),
     * the labels, citations or environments an argument takes, or a
     * bibliography entry's type after "@".
     */
    func completions(caret: UInt32, explicit: Bool, labels: [String], citations: [String])  -> Completions?
    
    /**
     * The editor replaced `length` units at `start` with `text`. A range
     * past the end is cut to the text: the mirror never fails the editor.
     */
    func edit(start: UInt32, length: UInt32, text: String) 
    
    /**
     * The highlighted runs of the lines a range touches.
     */
    func highlights(start: UInt32, length: UInt32)  -> [Highlight]
    
    /**
     * A block by its id (the catalog's `blocks`) in place of the selection,
     * on a line of its own; none for an id the catalog hasn't.
     */
    func insertBlock(id: String, selection: TextRange)  -> Insertion?
    
    /**
     * A maths symbol's command in place of the selection: as it is in
     * maths, and between dollars in text, where the bare command would stop
     * the build.
     */
    func insertSymbol(command: String, selection: TextRange)  -> Insertion
    
    /**
     * The line an offset is on, from 1.
     */
    func lineAt(offset: UInt32)  -> UInt32
    
    func lineCount()  -> UInt32
    
    /**
     * Where a line (from 1) starts; past the last line, the last line's start.
     */
    func lineStart(line: UInt32)  -> UInt32
    
    /**
     * The caret's line as a heading of `command` ("section"), or as plain
     * text given none, as a paragraph style does: a heading changes level
     * and keeps its title, a line of text becomes the title.
     */
    func setHeading(caret: UInt32, command: String)  -> Insertion
    
    func text()  -> String
    
    /**
     * "%" comments on or off for the lines the selections touch: off when
     * every one is already commented (or blank), on otherwise. In order;
     * the editor applies them from the last.
     */
    func toggleComment(selections: [TextRange])  -> [TextEdit]
    
}
/**
 * An open file's text, mirrored from the editor, and the answers about it.
 */
open class SourceDocument: SourceDocumentProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_texlocal_syntax_fn_clone_sourcedocument(self.handle, $0) }
    }
public convenience init(text: String) {
    let handle =
        try! rustCall() {
    uniffi_texlocal_syntax_fn_constructor_sourcedocument_new(
        FfiConverterString.lower(text),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_texlocal_syntax_fn_free_sourcedocument(handle, $0) }
    }

    

    
    /**
     * What to offer at the caret, if anything: commands after a backslash
     * (only once a letter follows unless `explicit`, asked for by the user),
     * the labels, citations or environments an argument takes, or a
     * bibliography entry's type after "@".
     */
open func completions(caret: UInt32, explicit: Bool, labels: [String], citations: [String]) -> Completions?  {
    return try!  FfiConverterOptionTypeCompletions.lift(try! rustCall() {
    uniffi_texlocal_syntax_fn_method_sourcedocument_completions(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(caret),
        FfiConverterBool.lower(explicit),
        FfiConverterSequenceString.lower(labels),
        FfiConverterSequenceString.lower(citations),$0
    )
})
}
    
    /**
     * The editor replaced `length` units at `start` with `text`. A range
     * past the end is cut to the text: the mirror never fails the editor.
     */
open func edit(start: UInt32, length: UInt32, text: String)  {try! rustCall() {
    uniffi_texlocal_syntax_fn_method_sourcedocument_edit(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(start),
        FfiConverterUInt32.lower(length),
        FfiConverterString.lower(text),$0
    )
}
}
    
    /**
     * The highlighted runs of the lines a range touches.
     */
open func highlights(start: UInt32, length: UInt32) -> [Highlight]  {
    return try!  FfiConverterSequenceTypeHighlight.lift(try! rustCall() {
    uniffi_texlocal_syntax_fn_method_sourcedocument_highlights(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(start),
        FfiConverterUInt32.lower(length),$0
    )
})
}
    
    /**
     * A block by its id (the catalog's `blocks`) in place of the selection,
     * on a line of its own; none for an id the catalog hasn't.
     */
open func insertBlock(id: String, selection: TextRange) -> Insertion?  {
    return try!  FfiConverterOptionTypeInsertion.lift(try! rustCall() {
    uniffi_texlocal_syntax_fn_method_sourcedocument_insert_block(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterTypeTextRange_lower(selection),$0
    )
})
}
    
    /**
     * A maths symbol's command in place of the selection: as it is in
     * maths, and between dollars in text, where the bare command would stop
     * the build.
     */
open func insertSymbol(command: String, selection: TextRange) -> Insertion  {
    return try!  FfiConverterTypeInsertion_lift(try! rustCall() {
    uniffi_texlocal_syntax_fn_method_sourcedocument_insert_symbol(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(command),
        FfiConverterTypeTextRange_lower(selection),$0
    )
})
}
    
    /**
     * The line an offset is on, from 1.
     */
open func lineAt(offset: UInt32) -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_texlocal_syntax_fn_method_sourcedocument_line_at(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(offset),$0
    )
})
}
    
open func lineCount() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_texlocal_syntax_fn_method_sourcedocument_line_count(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Where a line (from 1) starts; past the last line, the last line's start.
     */
open func lineStart(line: UInt32) -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_texlocal_syntax_fn_method_sourcedocument_line_start(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(line),$0
    )
})
}
    
    /**
     * The caret's line as a heading of `command` ("section"), or as plain
     * text given none, as a paragraph style does: a heading changes level
     * and keeps its title, a line of text becomes the title.
     */
open func setHeading(caret: UInt32, command: String) -> Insertion  {
    return try!  FfiConverterTypeInsertion_lift(try! rustCall() {
    uniffi_texlocal_syntax_fn_method_sourcedocument_set_heading(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(caret),
        FfiConverterString.lower(command),$0
    )
})
}
    
open func text() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_texlocal_syntax_fn_method_sourcedocument_text(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * "%" comments on or off for the lines the selections touch: off when
     * every one is already commented (or blank), on otherwise. In order;
     * the editor applies them from the last.
     */
open func toggleComment(selections: [TextRange]) -> [TextEdit]  {
    return try!  FfiConverterSequenceTypeTextEdit.lift(try! rustCall() {
    uniffi_texlocal_syntax_fn_method_sourcedocument_toggle_comment(
            self.uniffiCloneHandle(),
        FfiConverterSequenceTypeTextRange.lower(selections),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSourceDocument: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = SourceDocument

    public static func lift(_ handle: UInt64) throws -> SourceDocument {
        return SourceDocument(unsafeFromHandle: handle)
    }

    public static func lower(_ value: SourceDocument) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SourceDocument {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: SourceDocument, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSourceDocument_lift(_ handle: UInt64) throws -> SourceDocument {
    return try FfiConverterTypeSourceDocument.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSourceDocument_lower(_ value: SourceDocument) -> UInt64 {
    return FfiConverterTypeSourceDocument.lower(value)
}




public struct Completion: Equatable, Hashable {
    public var label: String
    /**
     * What it is ("sectioning"), empty for names from the project.
     */
    public var detail: String
    public var kind: CompletionKind
    /**
     * What goes in, with the fields' defaults and the line's indentation.
     */
    public var text: String
    /**
     * In order of position.
     */
    public var fields: [SnippetField]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(label: String, 
        /**
         * What it is ("sectioning"), empty for names from the project.
         */detail: String, kind: CompletionKind, 
        /**
         * What goes in, with the fields' defaults and the line's indentation.
         */text: String, 
        /**
         * In order of position.
         */fields: [SnippetField]) {
        self.label = label
        self.detail = detail
        self.kind = kind
        self.text = text
        self.fields = fields
    }

    

    
}

#if compiler(>=6)
extension Completion: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCompletion: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Completion {
        return
            try Completion(
                label: FfiConverterString.read(from: &buf), 
                detail: FfiConverterString.read(from: &buf), 
                kind: FfiConverterTypeCompletionKind.read(from: &buf), 
                text: FfiConverterString.read(from: &buf), 
                fields: FfiConverterSequenceTypeSnippetField.read(from: &buf)
        )
    }

    public static func write(_ value: Completion, into buf: inout [UInt8]) {
        FfiConverterString.write(value.label, into: &buf)
        FfiConverterString.write(value.detail, into: &buf)
        FfiConverterTypeCompletionKind.write(value.kind, into: &buf)
        FfiConverterString.write(value.text, into: &buf)
        FfiConverterSequenceTypeSnippetField.write(value.fields, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompletion_lift(_ buf: RustBuffer) throws -> Completion {
    return try FfiConverterTypeCompletion.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompletion_lower(_ value: Completion) -> RustBuffer {
    return FfiConverterTypeCompletion.lower(value)
}


/**
 * Completions for the text from `start` to the caret, which they replace.
 */
public struct Completions: Equatable, Hashable {
    public var start: UInt32
    public var items: [Completion]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(start: UInt32, items: [Completion]) {
        self.start = start
        self.items = items
    }

    

    
}

#if compiler(>=6)
extension Completions: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCompletions: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Completions {
        return
            try Completions(
                start: FfiConverterUInt32.read(from: &buf), 
                items: FfiConverterSequenceTypeCompletion.read(from: &buf)
        )
    }

    public static func write(_ value: Completions, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.start, into: &buf)
        FfiConverterSequenceTypeCompletion.write(value.items, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompletions_lift(_ buf: RustBuffer) throws -> Completions {
    return try FfiConverterTypeCompletions.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompletions_lower(_ value: Completions) -> RustBuffer {
    return FfiConverterTypeCompletions.lower(value)
}


public struct Highlight: Equatable, Hashable {
    public var start: UInt32
    public var length: UInt32
    public var kind: HighlightKind

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(start: UInt32, length: UInt32, kind: HighlightKind) {
        self.start = start
        self.length = length
        self.kind = kind
    }

    

    
}

#if compiler(>=6)
extension Highlight: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHighlight: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Highlight {
        return
            try Highlight(
                start: FfiConverterUInt32.read(from: &buf), 
                length: FfiConverterUInt32.read(from: &buf), 
                kind: FfiConverterTypeHighlightKind.read(from: &buf)
        )
    }

    public static func write(_ value: Highlight, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.start, into: &buf)
        FfiConverterUInt32.write(value.length, into: &buf)
        FfiConverterTypeHighlightKind.write(value.kind, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHighlight_lift(_ buf: RustBuffer) throws -> Highlight {
    return try FfiConverterTypeHighlight.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHighlight_lower(_ value: Highlight) -> RustBuffer {
    return FfiConverterTypeHighlight.lower(value)
}


/**
 * An edit and where the caret goes after it.
 */
public struct Insertion: Equatable, Hashable {
    public var edit: TextEdit
    public var caret: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(edit: TextEdit, caret: UInt32) {
        self.edit = edit
        self.caret = caret
    }

    

    
}

#if compiler(>=6)
extension Insertion: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeInsertion: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Insertion {
        return
            try Insertion(
                edit: FfiConverterTypeTextEdit.read(from: &buf), 
                caret: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: Insertion, into buf: inout [UInt8]) {
        FfiConverterTypeTextEdit.write(value.edit, into: &buf)
        FfiConverterUInt32.write(value.caret, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInsertion_lift(_ buf: RustBuffer) throws -> Insertion {
    return try FfiConverterTypeInsertion.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInsertion_lower(_ value: Insertion) -> RustBuffer {
    return FfiConverterTypeInsertion.lower(value)
}


/**
 * A place to type in a completion's text. Fields with the same `index`
 * are one field in several places: what's typed in one goes in all.
 */
public struct SnippetField: Equatable, Hashable {
    /**
     * From the start of the completion's text, in UTF-16 units.
     */
    public var start: UInt32
    public var length: UInt32
    /**
     * The field's place in the order Tab goes through them, from 0.
     */
    public var index: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * From the start of the completion's text, in UTF-16 units.
         */start: UInt32, length: UInt32, 
        /**
         * The field's place in the order Tab goes through them, from 0.
         */index: UInt32) {
        self.start = start
        self.length = length
        self.index = index
    }

    

    
}

#if compiler(>=6)
extension SnippetField: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSnippetField: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SnippetField {
        return
            try SnippetField(
                start: FfiConverterUInt32.read(from: &buf), 
                length: FfiConverterUInt32.read(from: &buf), 
                index: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: SnippetField, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.start, into: &buf)
        FfiConverterUInt32.write(value.length, into: &buf)
        FfiConverterUInt32.write(value.index, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSnippetField_lift(_ buf: RustBuffer) throws -> SnippetField {
    return try FfiConverterTypeSnippetField.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSnippetField_lower(_ value: SnippetField) -> RustBuffer {
    return FfiConverterTypeSnippetField.lower(value)
}


/**
 * Replace `length` units at `start` with `text`.
 */
public struct TextEdit: Equatable, Hashable {
    public var start: UInt32
    public var length: UInt32
    public var text: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(start: UInt32, length: UInt32, text: String) {
        self.start = start
        self.length = length
        self.text = text
    }

    

    
}

#if compiler(>=6)
extension TextEdit: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTextEdit: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TextEdit {
        return
            try TextEdit(
                start: FfiConverterUInt32.read(from: &buf), 
                length: FfiConverterUInt32.read(from: &buf), 
                text: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: TextEdit, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.start, into: &buf)
        FfiConverterUInt32.write(value.length, into: &buf)
        FfiConverterString.write(value.text, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTextEdit_lift(_ buf: RustBuffer) throws -> TextEdit {
    return try FfiConverterTypeTextEdit.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTextEdit_lower(_ value: TextEdit) -> RustBuffer {
    return FfiConverterTypeTextEdit.lower(value)
}


/**
 * A range of the text, in UTF-16 units.
 */
public struct TextRange: Equatable, Hashable {
    public var start: UInt32
    public var length: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(start: UInt32, length: UInt32) {
        self.start = start
        self.length = length
    }

    

    
}

#if compiler(>=6)
extension TextRange: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTextRange: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TextRange {
        return
            try TextRange(
                start: FfiConverterUInt32.read(from: &buf), 
                length: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: TextRange, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.start, into: &buf)
        FfiConverterUInt32.write(value.length, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTextRange_lift(_ buf: RustBuffer) throws -> TextRange {
    return try FfiConverterTypeTextRange.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTextRange_lower(_ value: TextRange) -> RustBuffer {
    return FfiConverterTypeTextRange.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum CompletionKind: Equatable, Hashable {
    
    case command
    case environment
    case label
    case citation
    case entryType





}

#if compiler(>=6)
extension CompletionKind: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCompletionKind: FfiConverterRustBuffer {
    typealias SwiftType = CompletionKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CompletionKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .command
        
        case 2: return .environment
        
        case 3: return .label
        
        case 4: return .citation
        
        case 5: return .entryType
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CompletionKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .command:
            writeInt(&buf, Int32(1))
        
        
        case .environment:
            writeInt(&buf, Int32(2))
        
        
        case .label:
            writeInt(&buf, Int32(3))
        
        
        case .citation:
            writeInt(&buf, Int32(4))
        
        
        case .entryType:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompletionKind_lift(_ buf: RustBuffer) throws -> CompletionKind {
    return try FfiConverterTypeCompletionKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompletionKind_lower(_ value: CompletionKind) -> RustBuffer {
    return FfiConverterTypeCompletionKind.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * What a run of text is, by the stex mode's token names. Plain text and
 * brackets have none.
 */

public enum HighlightKind: Equatable, Hashable {
    
    /**
     * `\command`, an escape (`\%`), `\\`, and maths' `^ _ &` (stex's tag).
     */
    case command
    /**
     * An environment's, package's, label's, reference's or citation's name,
     * and a number in text (atom).
     */
    case argument
    /**
     * `$ $$ \( \) \[ \]` (keyword).
     */
    case mathDelimiter
    /**
     * Letters in maths (variableName.special).
     */
    case mathIdentifier
    /**
     * A number in maths.
     */
    case number
    case comment
    /**
     * A stray closing brace, or what maths can't hold (error).
     */
    case invalid
    /**
     * `\importmodule`'s first argument (string).
     */
    case stringLiteral
    /**
     * Its second (builtin).
     */
    case builtin





}

#if compiler(>=6)
extension HighlightKind: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHighlightKind: FfiConverterRustBuffer {
    typealias SwiftType = HighlightKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HighlightKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .command
        
        case 2: return .argument
        
        case 3: return .mathDelimiter
        
        case 4: return .mathIdentifier
        
        case 5: return .number
        
        case 6: return .comment
        
        case 7: return .invalid
        
        case 8: return .stringLiteral
        
        case 9: return .builtin
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HighlightKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .command:
            writeInt(&buf, Int32(1))
        
        
        case .argument:
            writeInt(&buf, Int32(2))
        
        
        case .mathDelimiter:
            writeInt(&buf, Int32(3))
        
        
        case .mathIdentifier:
            writeInt(&buf, Int32(4))
        
        
        case .number:
            writeInt(&buf, Int32(5))
        
        
        case .comment:
            writeInt(&buf, Int32(6))
        
        
        case .invalid:
            writeInt(&buf, Int32(7))
        
        
        case .stringLiteral:
            writeInt(&buf, Int32(8))
        
        
        case .builtin:
            writeInt(&buf, Int32(9))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHighlightKind_lift(_ buf: RustBuffer) throws -> HighlightKind {
    return try FfiConverterTypeHighlightKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHighlightKind_lower(_ value: HighlightKind) -> RustBuffer {
    return FfiConverterTypeHighlightKind.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeCompletions: FfiConverterRustBuffer {
    typealias SwiftType = Completions?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeCompletions.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeCompletions.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeInsertion: FfiConverterRustBuffer {
    typealias SwiftType = Insertion?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeInsertion.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeInsertion.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeCompletion: FfiConverterRustBuffer {
    typealias SwiftType = [Completion]

    public static func write(_ value: [Completion], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCompletion.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Completion] {
        let len: Int32 = try readInt(&buf)
        var seq = [Completion]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCompletion.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeHighlight: FfiConverterRustBuffer {
    typealias SwiftType = [Highlight]

    public static func write(_ value: [Highlight], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeHighlight.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Highlight] {
        let len: Int32 = try readInt(&buf)
        var seq = [Highlight]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeHighlight.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSnippetField: FfiConverterRustBuffer {
    typealias SwiftType = [SnippetField]

    public static func write(_ value: [SnippetField], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSnippetField.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SnippetField] {
        let len: Int32 = try readInt(&buf)
        var seq = [SnippetField]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSnippetField.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeTextEdit: FfiConverterRustBuffer {
    typealias SwiftType = [TextEdit]

    public static func write(_ value: [TextEdit], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTextEdit.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [TextEdit] {
        let len: Int32 = try readInt(&buf)
        var seq = [TextEdit]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeTextEdit.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeTextRange: FfiConverterRustBuffer {
    typealias SwiftType = [TextRange]

    public static func write(_ value: [TextRange], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTextRange.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [TextRange] {
        let len: Int32 = try readInt(&buf)
        var seq = [TextRange]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeTextRange.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_texlocal_syntax_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_texlocal_syntax_checksum_method_sourcedocument_completions() != 53551) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_texlocal_syntax_checksum_method_sourcedocument_edit() != 43468) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_texlocal_syntax_checksum_method_sourcedocument_highlights() != 55404) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_texlocal_syntax_checksum_method_sourcedocument_insert_block() != 54139) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_texlocal_syntax_checksum_method_sourcedocument_insert_symbol() != 3454) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_texlocal_syntax_checksum_method_sourcedocument_line_at() != 60947) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_texlocal_syntax_checksum_method_sourcedocument_line_count() != 6408) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_texlocal_syntax_checksum_method_sourcedocument_line_start() != 47982) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_texlocal_syntax_checksum_method_sourcedocument_set_heading() != 22362) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_texlocal_syntax_checksum_method_sourcedocument_text() != 2274) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_texlocal_syntax_checksum_method_sourcedocument_toggle_comment() != 22604) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_texlocal_syntax_checksum_constructor_sourcedocument_new() != 27891) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureTexlocalSyntaxInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all