// Static completion data for the LaTeX editor.

export const ENVIRONMENTS = [
  'document', 'abstract', 'itemize', 'enumerate', 'description', 'figure', 'table',
  'tabular', 'array', 'equation', 'equation*', 'align', 'align*', 'gather', 'gather*',
  'multline', 'cases', 'matrix', 'pmatrix', 'bmatrix', 'vmatrix', 'center', 'flushleft',
  'flushright', 'quote', 'quotation', 'verbatim', 'lstlisting', 'minipage', 'frame',
  'theorem', 'lemma', 'proof', 'definition', 'corollary', 'example', 'remark',
  'algorithm', 'algorithmic', 'tikzpicture', 'thebibliography', 'titlepage', 'appendix',
];

// [name, detail, snippet] — snippet uses ${} for cursor placeholders
export const COMMANDS = [
  ['\\documentclass', 'class', '\\documentclass{#{article}}'],
  ['\\usepackage', 'package', '\\usepackage{#{}}'],
  ['\\begin', 'environment', '\\begin{#{env}}\n\t#{}\n\\end{#{env}}'],
  ['\\section', 'sectioning', '\\section{#{}}'],
  ['\\subsection', 'sectioning', '\\subsection{#{}}'],
  ['\\subsubsection', 'sectioning', '\\subsubsection{#{}}'],
  ['\\paragraph', 'sectioning', '\\paragraph{#{}}'],
  ['\\chapter', 'sectioning', '\\chapter{#{}}'],
  ['\\part', 'sectioning', '\\part{#{}}'],
  ['\\title', 'metadata', '\\title{#{}}'],
  ['\\author', 'metadata', '\\author{#{}}'],
  ['\\date', 'metadata', '\\date{#{\\today}}'],
  ['\\maketitle', 'metadata', '\\maketitle'],
  ['\\tableofcontents', 'structure', '\\tableofcontents'],
  ['\\label', 'reference', '\\label{#{}}'],
  ['\\ref', 'reference', '\\ref{#{}}'],
  ['\\eqref', 'reference', '\\eqref{#{}}'],
  ['\\pageref', 'reference', '\\pageref{#{}}'],
  ['\\cite', 'citation', '\\cite{#{}}'],
  ['\\citep', 'citation', '\\citep{#{}}'],
  ['\\citet', 'citation', '\\citet{#{}}'],
  ['\\footnote', 'text', '\\footnote{#{}}'],
  ['\\textbf', 'text', '\\textbf{#{}}'],
  ['\\textit', 'text', '\\textit{#{}}'],
  ['\\texttt', 'text', '\\texttt{#{}}'],
  ['\\textsc', 'text', '\\textsc{#{}}'],
  ['\\underline', 'text', '\\underline{#{}}'],
  ['\\emph', 'text', '\\emph{#{}}'],
  ['\\mbox', 'text', '\\mbox{#{}}'],
  ['\\verb', 'text', '\\verb|#{}|'],
  ['\\item', 'list', '\\item '],
  ['\\includegraphics', 'graphics', '\\includegraphics[width=#{0.8}\\linewidth]{#{}}'],
  ['\\caption', 'float', '\\caption{#{}}'],
  ['\\centering', 'float', '\\centering'],
  ['\\frac', 'math', '\\frac{#{}}{#{}}'],
  ['\\dfrac', 'math', '\\dfrac{#{}}{#{}}'],
  ['\\sqrt', 'math', '\\sqrt{#{}}'],
  ['\\sum', 'math', '\\sum_{#{}}^{#{}}'],
  ['\\prod', 'math', '\\prod_{#{}}^{#{}}'],
  ['\\int', 'math', '\\int_{#{}}^{#{}}'],
  ['\\lim', 'math', '\\lim_{#{}}'],
  ['\\infty', 'math', '\\infty'],
  ['\\partial', 'math', '\\partial'],
  ['\\nabla', 'math', '\\nabla'],
  ['\\cdot', 'math', '\\cdot'],
  ['\\times', 'math', '\\times'],
  ['\\pm', 'math', '\\pm'],
  ['\\leq', 'math', '\\leq'],
  ['\\geq', 'math', '\\geq'],
  ['\\neq', 'math', '\\neq'],
  ['\\approx', 'math', '\\approx'],
  ['\\equiv', 'math', '\\equiv'],
  ['\\rightarrow', 'math', '\\rightarrow'],
  ['\\Rightarrow', 'math', '\\Rightarrow'],
  ['\\leftarrow', 'math', '\\leftarrow'],
  ['\\mapsto', 'math', '\\mapsto'],
  ['\\forall', 'math', '\\forall'],
  ['\\exists', 'math', '\\exists'],
  ['\\in', 'math', '\\in'],
  ['\\subset', 'math', '\\subset'],
  ['\\subseteq', 'math', '\\subseteq'],
  ['\\cup', 'math', '\\cup'],
  ['\\cap', 'math', '\\cap'],
  ['\\emptyset', 'math', '\\emptyset'],
  ['\\mathbb', 'math', '\\mathbb{#{}}'],
  ['\\mathcal', 'math', '\\mathcal{#{}}'],
  ['\\mathbf', 'math', '\\mathbf{#{}}'],
  ['\\mathrm', 'math', '\\mathrm{#{}}'],
  ['\\operatorname', 'math', '\\operatorname{#{}}'],
  ['\\hat', 'math', '\\hat{#{}}'],
  ['\\bar', 'math', '\\bar{#{}}'],
  ['\\tilde', 'math', '\\tilde{#{}}'],
  ['\\vec', 'math', '\\vec{#{}}'],
  ['\\dot', 'math', '\\dot{#{}}'],
  ['\\alpha', 'greek', '\\alpha'], ['\\beta', 'greek', '\\beta'], ['\\gamma', 'greek', '\\gamma'],
  ['\\delta', 'greek', '\\delta'], ['\\epsilon', 'greek', '\\epsilon'], ['\\varepsilon', 'greek', '\\varepsilon'],
  ['\\zeta', 'greek', '\\zeta'], ['\\eta', 'greek', '\\eta'], ['\\theta', 'greek', '\\theta'],
  ['\\iota', 'greek', '\\iota'], ['\\kappa', 'greek', '\\kappa'], ['\\lambda', 'greek', '\\lambda'],
  ['\\mu', 'greek', '\\mu'], ['\\nu', 'greek', '\\nu'], ['\\xi', 'greek', '\\xi'],
  ['\\pi', 'greek', '\\pi'], ['\\rho', 'greek', '\\rho'], ['\\sigma', 'greek', '\\sigma'],
  ['\\tau', 'greek', '\\tau'], ['\\upsilon', 'greek', '\\upsilon'], ['\\phi', 'greek', '\\phi'],
  ['\\varphi', 'greek', '\\varphi'], ['\\chi', 'greek', '\\chi'], ['\\psi', 'greek', '\\psi'],
  ['\\omega', 'greek', '\\omega'], ['\\Gamma', 'greek', '\\Gamma'], ['\\Delta', 'greek', '\\Delta'],
  ['\\Theta', 'greek', '\\Theta'], ['\\Lambda', 'greek', '\\Lambda'], ['\\Sigma', 'greek', '\\Sigma'],
  ['\\Phi', 'greek', '\\Phi'], ['\\Psi', 'greek', '\\Psi'], ['\\Omega', 'greek', '\\Omega'],
  ['\\left', 'math', '\\left(#{}\\right)'],
  ['\\bigl', 'math', '\\bigl(#{}\\bigr)'],
  ['\\text', 'math', '\\text{#{}}'],
  ['\\newcommand', 'definition', '\\newcommand{\\#{name}}{#{}}'],
  ['\\renewcommand', 'definition', '\\renewcommand{\\#{name}}{#{}}'],
  ['\\newenvironment', 'definition', '\\newenvironment{#{name}}{#{}}{#{}}'],
  ['\\input', 'file', '\\input{#{}}'],
  ['\\include', 'file', '\\include{#{}}'],
  ['\\bibliography', 'bibliography', '\\bibliography{#{}}'],
  ['\\bibliographystyle', 'bibliography', '\\bibliographystyle{#{plain}}'],
  ['\\printbibliography', 'bibliography', '\\printbibliography'],
  ['\\addbibresource', 'bibliography', '\\addbibresource{#{}}'],
  ['\\hspace', 'spacing', '\\hspace{#{1em}}'],
  ['\\vspace', 'spacing', '\\vspace{#{1em}}'],
  ['\\newpage', 'spacing', '\\newpage'],
  ['\\clearpage', 'spacing', '\\clearpage'],
  ['\\noindent', 'spacing', '\\noindent'],
  ['\\linebreak', 'spacing', '\\linebreak'],
  ['\\hline', 'table', '\\hline'],
  ['\\toprule', 'table', '\\toprule'],
  ['\\midrule', 'table', '\\midrule'],
  ['\\bottomrule', 'table', '\\bottomrule'],
  ['\\multicolumn', 'table', '\\multicolumn{#{2}}{#{c}}{#{}}'],
  ['\\multirow', 'table', '\\multirow{#{2}}{*}{#{}}'],
  ['\\today', 'misc', '\\today'],
  ['\\LaTeX', 'misc', '\\LaTeX'],
  ['\\TeX', 'misc', '\\TeX'],
  ['\\ldots', 'misc', '\\ldots'],
  ['\\dots', 'misc', '\\dots'],
  ['\\%', 'escape', '\\%'], ['\\&', 'escape', '\\&'], ['\\$', 'escape', '\\$'],
  ['\\_', 'escape', '\\_'], ['\\#', 'escape', '\\#'], ['\\{', 'escape', '\\{'], ['\\}', 'escape', '\\}'],
];

export const BIB_ENTRY_TYPES = [
  'article', 'book', 'inbook', 'incollection', 'inproceedings', 'conference',
  'manual', 'mastersthesis', 'phdthesis', 'misc', 'techreport', 'unpublished', 'online',
];
